### ISSUE TITLE
Error when filtering column and culture <> en-US

### ISSUE THREAD

**Issue by oxxa** [syncfusion/ej2-grids#3]
Please see plnkr  http://plnkr.co/edit/wqvEgA8nATeDKU7xKZIG?p=preview  which is an adaption from an example in the docs.  The string columns will filter fine but the numeric or dates ones (the first two) will not.  They show the following error:

```
Error: The specified locale or controlname not found in the locale object
    at Object.y [as throwError] (http://cdn.syncfusion.com/ej2/ej2-base/dist/ej2-base.umd.min.js:11:3873)
    at e.setLocale (http://cdn.syncfusion.com/ej2/ej2-base/dist/ej2-base.umd.min.js:13:24597)
    at new e (http://cdn.syncfusion.com/ej2/ej2-base/dist/ej2-base.umd.min.js:13:24443)
    at t.preRender (http://cdn.syncfusion.com/ej2/ej2-inputs/dist/ej2-inputs.umd.min.js:11:2919)
    at t.appendTo (http://cdn.syncfusion.com/ej2/ej2-base/dist/ej2-base.umd.min.js:12:6090)
    at e.create (http://cdn.syncfusion.com/ej2/ej2-grids/dist/ej2-grids.umd.min.js:20:6631)
    at e.renderFlValueUI (http://cdn.syncfusion.com/ej2/ej2-grids/dist/ej2-grids.umd.min.js:20:951)
    at e.renderFilterUI (http://cdn.syncfusion.com/ej2/ej2-grids/dist/ej2-grids.umd.min.js:20:479)
    at e.dialogCreated (http://cdn.syncfusion.com/ej2/ej2-grids/dist/ej2-grids.umd.min.js:20:139)
    at e.notify (http://cdn.syncfusion.com/ej2/ej2-base/dist/ej2-base.umd.min.js:11:19332)
```

Note that I'm slightly confused if I should be importing the cldr data or not as the example does not but other examples on the site do?

Also I am expecting the date column to show values in the German format of dd.MM.YY but it is showing  in US format (MM/dd/yy), what can I do to fix that?

**Comment by oxxa** [comment]
Ok, I've tracked this down to an unfortunate choice of test locale (de-DE) which did not match to json files in cldr.  Switching to 'en-GB' works for me so I'm happy with that.  The second part of the answer was that from I10n.js where it throws if there is no entry for the control in your string map, ie to get datepicker to work in the grid I had to add an empty key:

```
L10n.load({
  'en-GB': {
    'grid': {
      'EmptyRecord': '&nbsp;'
    },
    'pager': {},
    'datepicker': {}
  }
});
```

I'm happy for this to be closed as I've found a workaround.

**Comment by pavithra95subramaniam** [comment]
Hi Oxxa,

**Query #1:** Numeric and date columns filtering throws script error.

We have confirmed “Filtermenu thorws script error for numeric and date columns with localization” as bug and logged a report for the same. The fix will be available on November 23, 2017 release.

**Query #2:**  I am expecting the date column to show values in the German format of dd.MM.YY.

You can set **“column.format”**  property as **“yMMdd”**  to achieve your requirement. Please refer the following sample link.

Sample Link: http://plnkr.co/edit/vmxmIs6mIBKNzh4vQxnk?p=preview 

Regards,
Pavithra S.

**Comment by pavithra95subramaniam** [comment]
Hi Oxxa,

Thanks for your patience.   
 
We are glad to announce that our Essential Studio Volume 4(v 15.4.19) release is rolled out successfully and In that release, we have added the fix for “Filtermenu throws script error for numeric and date columns with localization”  issue.

Please let us know if you have any queries.

Regards,   
Pavithra S.
